model:
    arch: hardnet
image_src: /usb_camerac/image_raw
data:
    dataset: bdd100k
    train_split: train
    val_split: val
    img_rows: 576
    img_cols: 1024
    path: /home/jimmyyoung/data/bdd100k/
    sbd_path: /mnt/ssd2/Cityscapes/
testing:
    resume: 'weights/hardnet70_cityscapes_model_2.pkl'
    type: image
    n_classes: 19
    publish_rate: 4
    erode_kernel: 3
    sample_delta: 15
    sample_delta_start: 15
camera:
    center_point: 600
    left_threshold: 0.7
    right_threshold: 0.7
vis:
    colors: [  # [  0,   0,   0],
        [128, 64, 128],
        [244, 35, 232],
        [70, 70, 70],
        [102, 102, 156],
        [190, 153, 153],
        [153, 153, 153],
        [250, 170, 30],
        [220, 220, 0],
        [107, 142, 35],
        [152, 251, 152],
        [0, 130, 180],
        [220, 20, 60],
        [255, 0, 0],
        [0, 0, 142],
        [0, 0, 70],
        [0, 60, 100],
        [0, 80, 100],
        [0, 0, 230],
        [119, 11, 32],
    ]
    






    