model:
    arch: hardnet
data:
    dataset: bdd100k
    train_split: train
    val_split: val
    img_rows: 576
    img_cols: 1024
    path: /home/jimmyyoung/data/bdd100k/
    sbd_path: /mnt/ssd2/Cityscapes/
training:
    train_iters: 90000
    batch_size: 16
    val_interval: 15000
    n_workers: 4
    print_interval: 20
    print_interval_image: 100
    augmentations:
        hflip: 0.5
        rscale_crop: [1024, 576]
        gamma: 0.1
        rotate: 15
        hue: 0.05
        saturation: 0.05
        brightness: 0.05
    optimizer:
        name: 'sgd'
        lr: 0.02
        weight_decay: 0.0005
        momentum: 0.9
    loss:
        name: 'bootstrapped_cross_entropy'
        min_K: 4096
        loss_th: 0.3
        size_average: True
    lr_schedule: 
        name: 'poly_lr'
        max_iter: 90000
    resume: '/home/jimmyyoung/FCHarDNet/weights/hardnet_bdd100k_checkpoint.pkl'
    finetune: None    
